name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ '165.245.251.242' }}
          username: ${{ 'juanes' }}
          key: ${{ '-----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACCTASNu7tCGYtvwn+PL1P2A+xpoj0k0tAl8bPY0H2dNZAAAAKB94jK1feIytQAAAAtzc2gtZWQyNTUxOQAAACCTASNu7tCGYtvwn+PL1P2A+xpoj0k0tAl8bPY0H2dNZAAAAEAYZlue8KXsXRybAxqGHcZcE7eHcGlwtgYeYHhze/FNMJMBI27u0IZi2/Cf48vU/YD7GmiPSTS0CXxs9jQfZ01kAAAAG2p1YW5lc0B1YnVudHUtanVhbnByYWN0aWNhcwEC-----END OPENSSH PRIVATE KEY-----' }}
          script: |
            cd /home/juanes/repositories/tfm-ai-juanserver
            git pull
            cd /home/juanes/repositories
            docker compose up -d --no-deps --build frontend
