name: Deploy Frontend DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH to DEV
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/juanes/repos_dev/dev-frontend
            git pull
            cd /home/juanes/repos_dev
            docker compose -f docker-compose-dev.yml up -d --no-deps --build dev_frontend
